name: Scrape Composites Template

on:
  workflow_call:
    inputs:
      server-offset:
        required: true
        type: number
      client-digits:
        required: true
        type: number
env:
  CARGO_TERM_COLOR: always
jobs:
  C:
    strategy:
      fail-fast: false
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.client-digits }}-${{ inputs.server-offset }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Factorize
      run: |
           export server_digits=$((${{ inputs.client-digits }} + ${{ inputs.server-offset }}))
           if [ ${server_digits} -lt 90 ]; then
             export server_digits=90
           fi
           (
             csv="C${server_digits}.csv"
             echo "Fetching file C${server_digits}.csv"
             nice -+19 git lfs pull -I "${csv}" || (
               nice -+19 wget "http://5.199.134.142/composite/${csv}.zst"
               nice -+19 unzstd -f "${csv}.zst"
             )
           ) &
           (
             let "start = $(($SRANDOM % 100001))"
             curl -Ss --retry 10 --retry-all-errors "https://factordb.com/listtype.php?t=3&mindig=${server-digits}&perpage=5000&start=${start}" \
                 | grep -o "id=[0-9]\+" \
                 | uniq \
                 | grep -o "[0-9]\+" \
                 | nice -+19 ./scrape-composites-server-side.sh
             echo "Handling file C${server_digits}.csv"
             source=${csv} nice -+19 ./scrape-composites-server-side-from-dump.sh
           ) &
           (
             sudo apt-get install libecm1
             digits=${{ inputs.client-digits }} ./scrape-composites-large-ci.sh
           ) &
           client=$!
           (
             sleep 19800
             killall -HUP parallel
             rm /tmp/delete_*
             rm /tmp/scrape-composites-fifo
             sleep 1200
             pkill msieve && sleep 5
             pkill curl
           ) &
           wait $client
    - uses: actions/upload-artifact@v4
      with:
        name: Failed Submissions
        path: failed-submissions.csv
        if-no-files-found: ignore
