name: Scrape Composites

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 3,6"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false
jobs:
  wave_1:
    strategy:
      matrix:
        client-digits: [81,83,85,87,89]
        server-offset: [10,40,70,100,130,160,190]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_2:
    needs: wave_1
    strategy:
      matrix:
        client-digits: [82,84,86,88,90]
        server-offset: [10,40,70,100,130,160,190]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_3:
    needs: wave_2
    strategy:
      matrix:
        client-digits: [81,83,85,87,89]
        server-offset: [20,50,80,110,140,170,200]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_4:
    needs: wave_3
    strategy:
      matrix:
        client-digits: [82,84,86,88,90]
        server-offset: [20,50,80,110,140,170,200]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_5:
    needs: wave_4
    strategy:
      matrix:
        client-digits: [81,83,85,87,89]
        server-offset: [30,60,90,120,150,180,210]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_6:
    needs: wave_5
    strategy:
      matrix:
        client-digits: [82,84,86,88,90]
        server-offset: [30,60,90,120,150,180,210]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_7_80_90:
    needs: wave_6
    uses: ./.github/workflows/template.yml
    with:
      client-digits: 80
      server-offset: 10
  wave_7_90:
    strategy:
      matrix:
        server-offset: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
    needs: wave_6
    uses: ./.github/workflows/template.yml
    with:
      client-digits: 90
      server-offset: 0
  wave_7_91:
    strategy:
      matrix:
        server-offset: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
    needs: wave_6
    uses: ./.github/workflows/template.yml
    with:
      client-digits: 91
      server-offset: ${{ matrix.server-offset }}

