name: Scrape Composites

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 3,6"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false
jobs:
  wave_1:
    strategy:
      matrix:
        client-digits: [81,83,85,87,89,91,93,95,97,99]
        server-offset: [20,60,100,140,180]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_2:
    needs: wave_1
    strategy:
      matrix:
        client-digits: [82,84,86,88,90,92,94,96,98,100]
        server-offset: [20,60,100,140,180]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_3:
    needs: wave_2
    strategy:
      matrix:
        client-digits: [81,83,85,87,89,91,93,95,97,99]
        server-offset: [40,80,120,160,200]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_4:
    needs: wave_3
    strategy:
      matrix:
        client-digits: [82,84,86,88,90,92,94,96,98,100]
        server-offset: [40,80,120,160,200]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_5:
    needs: wave_4
    strategy:
      matrix:
        client-digits: [80,81,82,83,84,85,86,87,88,89]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: 10

