name: Scrape Composites

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 3,6"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false
jobs:
  wave_1:
    strategy:
      matrix:
        server-offset: [10,40,70,100,130,160,190]
    uses: ./.github/workflows/template.yml
    with:
      server-offset: ${{ matrix.server-offset }}
  wave_2:
    needs: wave_1
    strategy:
      matrix:
        server-offset: [20,50,80,110,140,170,200]
    uses: ./.github/workflows/template.yml
    with:
      server-offset: ${{ matrix.server-offset }}
  wave_3:
    needs: wave_2
    strategy:
      matrix:
        server-offset: [30,60,90,120,150,180,210]
    uses: ./.github/workflows/template.yml
    with:
      server-offset: ${{ matrix.server-offset }}
