name: Scrape Composites

on:
  push:
    paths:
      - '.github/**'
      - 'scrape-composites-ci.sh'
      - 'scrape-composites-large-ci.sh'
      - '*.csv'
  pull_request:
    paths:
      - '.github/**'
      - 'scrape-composites-ci.sh'
      - 'scrape-composites-large-ci.sh'
      - '*.csv'
  schedule:
    - cron: "0 0 1,4,7,9,12,15,18,20,23,26,28 * *"
  workflow_dispatch:
jobs:
  C:
    strategy:
      max-parallel: 19
      matrix:
        client-digits: [90,91,85,96,82,93,87,98,81,92,89,100,83,94,84,95,86,97,88,99]
        server-offset: [120,100,160,60,180,80,140,40,200,20]
        include: # GITHUB FIXME: Let us use either multiple matrices, or lists in `include`
          - server-offset: 10
            client-digits: 85
          - server-offset: 10
            client-digits: 82
          - server-offset: 10
            client-digits: 88
          - server-offset: 10
            client-digits: 81
          - server-offset: 10
            client-digits: 86
          - server-offset: 10
            client-digits: 84
          - server-offset: 10
            client-digits: 89
          - server-offset: 10
            client-digits: 80
          - server-offset: 10
            client-digits: 90
          - server-offset: 10
            client-digits: 83
          - server-offset: 10
            client-digits: 87
    concurrency:
      group: ${{ github.event.pull_request.number || github.ref }}-${{ matrix.client-digits}}-${{ matrix.server-offset }}
      cancel-in-progress: false
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}

