name: Scrape Composites

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0,6,12,18 * * *" 
env:
  CARGO_TERM_COLOR: always

jobs:
  server-side:
    strategy:
      matrix:
        source: ['C90.csv', 'C91.csv']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: timeout 330m source=${{ matrix.source }} ./scrape-composites-server-side.sh
  client-side:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: timeout 330m ./scrape-composites-large-ci.sh
