name: Scrape Composites

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0,6,12,18 * * *" 
env:
  CARGO_TERM_COLOR: always

jobs:
  server-side:
    strategy:
      matrix:
        source: ['C90.csv', 'C91.csv']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: source=${{ matrix.source }} timeout 330m ./scrape-composites-server-side.sh
  client-side:
    strategy:
      matrix:
        digits: [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install libecm1
    - run: digits=${{ matrix.digits }} timeout 330m ./scrape-composites-large-ci.sh
