name: Scrape Composites

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 1,4,7,9,12,15,18,20,23,26,28 * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false
jobs:
  wave_1:
    strategy:
      matrix:
        client-digits: [81,83,85,87,89,91,93,95,97,99]
        server-offset: [20,60,100,140,180]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_1a:
    strategy:
      matrix:
        client-digits: [80,89]
        server-offset: [0,10]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_2:
    needs: ['wave_1', 'wave_1a']
    strategy:
      matrix:
        client-digits: [82,84,86,88,90,92,94,96,98,100]
        server-offset: [20,60,100,140,180]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_2a:
    needs: ['wave_1', 'wave_1a']
    strategy:
      matrix:
        client-digits: [83,86,90]
        server-offset: [0,10]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_3:
    needs: ['wave_2', 'wave_2a']
    strategy:
      matrix:
        client-digits: [81,83,85,87,89,91,93,95,97,99]
        server-offset: [40,80,120,160,200]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_3a:
    needs: ['wave_2', 'wave_2a']
    strategy:
      matrix:
        client-digits: [81,84,87]
        server-offset: [0,10]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_4:
    needs: ['wave_3', 'wave_3a']
    strategy:
      matrix:
        client-digits: [82,84,86,88,90,92,94,96,98,100]
        server-offset: [40,80,120,160,200]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}
  wave_4a:
    needs: ['wave_3', 'wave_3a']
    strategy:
      matrix:
        client-digits: [82,85,88]
        server-offset: [0,10]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}

