name: Scrape Composites

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 3,6"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false
jobs:
  small:
    strategy:
      matrix:
        server-offset: [10,20,30,40,50,60,70]
    uses: ./.github/workflows/template.yml
    with:
      server-offset: ${{ matrix.server-offset }}
  medium:
    needs: small
    strategy:
      matrix:
        server-offset: [80,90,100,110,120,130,140]
    uses: ./.github/workflows/template.yml
    with:
      server-offset: ${{ matrix.server-offset }}
  large:
    needs: medium
    strategy:
      matrix:
        server-offset: [150,160,170,180,190,200,210]
    uses: ./.github/workflows/template.yml
    with:
      server-offset: ${{ matrix.server-offset }}
