name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0,6,12,18 * * *" 
env:
  CARGO_TERM_COLOR: always

jobs:
  server-side:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: scrape-composites-server-side.sh
