name: Scrape Composites

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 1,4,7,9,12,15,18,20,23,26,28 * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false
jobs:
  composites:
    strategy:
      matrix:
        max-parallel: 19
        client-digits: [81,85,89,93,97,82,86,90,94,98,83,87,91,95,99,84,88,92,96,100]
        server-offset: [20,60,100,140,180,40,80,120,160,200]
        include:
          - server-offset: 10
            client-digits: [80,81,82,83,84,85,86,87,88,89,90]
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}

