name: Scrape Composites Template

on:
  workflow_call:
    inputs:
      server-offset:
        required: true
        type: number
      client-digits:
        required: true
        type: number
env:
  CARGO_TERM_COLOR: always
jobs:
  C:
    strategy:
      fail-fast: false
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ inputs.client-digits }}-${{ inputs.server-offset }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Factorize
      run: |
           export server_digits=$((${{ inputs.client-digits }} + ${{ inputs.server-offset }}))
           if [ ${server_digits} -lt 90 ]; then
             export server_digits=90
           fi
           csv="C${server_digits}.csv"
           (
             git lfs pull -I "${csv}" || (
               wget "http://5.199.134.142/composite/${csv}.zst"
               unzstd -f "${csv}.zst"
             )
             source=${csv} nice -+19 ./scrape-composites-server-side.sh
           ) &
           (
             sudo apt-get install libecm1
             digits=${{ inputs.client-digits }} ./scrape-composites-large-ci.sh
           ) &
           client=$!
           sleep 19800
           killall -HUP parallel
           rm /tmp/delete_*
           pkill msieve
           wait $client
