name: Scrape Composites Template

on:
  workflow_call:
    inputs:
      server-offset:
        required: true
        type: number
      client-digits:
        required: true
        type: number
env:
  CARGO_TERM_COLOR: always
jobs:
  composites:
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v4
    - run: |
           export csv=C$((${{ inputs.client-digits }} + ${{ inputs.server-offset }})).csv
           (
             git lfs pull -I $csv || (
               wget "http://5.199.134.142/composite/${csv}.zst"
               unzstd -f "${csv}.zst"
             )
             source=${csv} timeout 330m nice -+19 ./scrape-composites-server-side.sh || true
           ) &
           sudo apt-get install libecm1
           digits=${{ inputs.client-digits }} timeout 330m ./scrape-composites-large-ci.sh || true
