name: Wave 1

on:
  push:
    paths:
      - '.github/**'
      - 'scrape-composites-ci.sh'
      - 'scrape-composites-large-ci.sh'
      - '*.csv'
  pull_request:
    paths:
      - '.github/**'
      - 'scrape-composites-ci.sh'
      - 'scrape-composites-large-ci.sh'
      - '*.csv'
  schedule:
    - cron: "0 0 3,6,8,11,14,17,19,22,25,27,30 * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}-wave1
  cancel-in-progress: false
jobs:
  C:
    strategy:
      max-parallel: 19
      matrix:
        client-digits: [90,91,85,96]
        server-offset: [120,100,160,60,180,80,140,40,200,20]
    concurrency:
      group: ${{ github.event.pull_request.number || github.ref }}-${{ matrix.client-digits}}-${{ matrix.server-offset }}
      cancel-in-progress: false
    uses: ./.github/workflows/template.yml
    with:
      client-digits: ${{ matrix.client-digits }}
      server-offset: ${{ matrix.server-offset }}

